### ISSUE TITLE
data.zip cannot be downloaded

### ISSUE THREAD

**Issue by ldincredible** [windingwind/minimal-IK-pytorch#2]
Hi, the data cannot be downloaded. Can you help me?
![image](https://user-images.githubusercontent.com/55923060/208391098-80a973ed-dcc7-4fac-9ab6-90f9a29c2fe3.png)

**Comment by windingwind** [comment]
Sorry for the late reply. I’m sick these days.

I’m not sure what is happening with the Onedrive shares. What about Google Drive? Or I could mail you directly.

Best,

**Comment by windingwind** [comment]
Try this link: https://zjueducn-my.sharepoint.com/:u:/g/personal/xy_wong_zju_edu_cn/EZSE66yWPgpFigG6nK9wM6QBx_PlXPwlzAy-xo5dSxvDXw?e=tbufQu

**Comment by ldincredible** [comment]
thank you.
best,
