### ISSUE TITLE
Hello,this data.zip cannot be  downloaded. Can you help me?My email is 2509272245@qq.com.

### ISSUE THREAD

**Issue by Cliny7** [windingwind/minimal-IK-pytorch#3]
![image](https://github.com/windingwind/minimal-IK-pytorch/assets/90387773/72854953-81e6-4973-8144-085fd1ea0587)

**Comment by windingwind** [comment]
https://zjueducn-my.sharepoint.com/:u:/g/personal/xy_wong_zju_edu_cn/EZSE66yWPgpFigG6nK9wM6QBx_PlXPwlzAy-xo5dSxvDXw?e=wzw6e3

**Comment by EvenGu** [comment]
The above link has expired again. Could you please reshare?
